
name: Test for a valid changelog entries

on:
    pull_request:

jobs:
    
    test:
        name: Check if the changelog was updated
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout the app
                uses: actions/checkout@v2
                with:
                    fetch-depth: 2
            
            -   name: Get the diff
                id: diff
                run: |
                    git diff HEAD~1 -- CHANGELOG.md
                    lines=$(git diff HEAD~1 -- CHANGELOG.md | wc -l)
                    echo "::set-output name=lines::$lines"
            
            -   name: Error if the number of diff lines is zero
                run: |
                    echo "::error file=CHANGELOG.md::There was no change in the changelog detected. Please fill in a valid entry into that file."
                    exit 1
                if: ${{ steps.diff.outputs.lines == 0 }}
