
name: CI-tests

on:
  push:
  pull_request:

jobs:
  
  test:
    name: Run the unittests
    runs-on: ubuntu-latest
    
    continue-on-error: ${{ matrix.mayFail }}
    
    strategy:
        fail-fast: false
        matrix:
            database:
                - mysql
                - pgsql
                - sqlite
            coreVersion:
                - stable19
            phpVersion:
                - "7"
            mayFail:
                - false
            include:
                # Test different core versions additionally
                -   database: mysql
                    coreVersion: stable18
                    phpVersion: "7"
                    mayFail: false
                -   database: mysql
                    coreVersion: stable20
                    phpVersion: "7"
                    mayFail: false
                
                # Test different PHP versions additionally
                -   database: mysql
                    coreVersion: stable19
                    phpVersion: "7.2"
                    mayFail: false
                    
                # Test against master (optionally)
                -   database: mysql
                    coreVersion: master
                    phpVersion: "7"
                    mayFail: true
                    
    steps:
      - name: Checkout the nextcloud server
        uses: actions/checkout@v2
        with:
            repository: nextcloud/server
            ref: ${{ matrix.coreVersion }}
            path: nextcloud
      - name: Checkout the app
        uses: actions/checkout@v2
        with:
            path: cookbook
      
      #- name: Docker Layer Caching
        #uses: satackey/action-docker-layer-caching@v0.0.8
        
      - name: Run the tests in docker container
        uses: ./cookbook/.github/actions/run-tests
        with:
            db: ${{ matrix.database }}
            phpVersion: ${{ matrix.phpVersion }}
    
      - name: Upload the log file
        uses: actions/upload-artifact@v2
        with:
            name: Nextcloud-logs (${{matrix.database}}, ${{matrix.coreVersion}}, ${{matrix.phpVersion}})
            path: nextcloud/data/nextcloud.log
